package com.constructor;

public class Cr2 {
        // default constructor
	//default constructor is only generated by the compiler
	public static void main(String[] args) {
	System.out.println("This is default constructor");

	}

}
